### ISSUE TITLE
Handle binary data being occasionally dumped out by `git diff`

### ISSUE THREAD

**Issue by floatplane** [floatplane/git_pr#30]
bug report:

```
peter [5:01 PM] 
this is a new thing from `git-pr`  
/Library/Ruby/Gems/2.0.0/gems/git-1.2.8/lib/git/diff.rb:121:in `split': invalid byte sequence in UTF-8 (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/git-1.2.8/lib/git/diff.rb:121:in `process_full_diff'
    from /Library/Ruby/Gems/2.0.0/gems/git-1.2.8/lib/git/diff.rb:107:in `process_full'
    from /Library/Ruby/Gems/2.0.0/gems/git-1.2.8/lib/git/diff.rb:64:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/git_pr-0.0.13/lib/git_pr/merge.rb:55:in `any?'
    from /Library/Ruby/Gems/2.0.0/gems/git_pr-0.0.13/lib/git_pr/merge.rb:55:in `merge_pull_cleanly'
    from /Library/Ruby/Gems/2.0.0/gems/git_pr-0.0.13/bin/git-pr:217:in `<top (required)>'
    from /usr/bin/git-pr:23:in `load'
    from /usr/bin/git-pr:23:in `<main>'

​[5:01] 
when I run
~/gitclients/Paper (develop) $ git pr merge 4851
```

solution:

```
brian [8:58 AM] 
ok so your git_pr deal was this: your branch was pretty diverged from origin/develop (a manual rebase would have made this go away). one of the files that was different in the branches was `lib/FiftyThreeSDK/docs/FiftyThree-Trademark-Guidelines/FiftyThree-Trademark-Guidlines.pdf`, which has embedded binary parts. somehow git didn't recognize it as binary, so `git diff` was printing binary data instead of just saying "Binary file changed"

​[8:59] 
now i know for next time.

peter [8:59 AM] 
Hah

​[9:00] 
Odd - yeah that explains the gigantic binary thing that it spit out
```

**Comment by floatplane** [comment]
Fixed
